@startuml BattleUI
class BattleUI{
    ' - enemyHealthBar : HealthBar
    ' - playerHealthBar : HealthBar
    ' - enemyLogPane : LogPane
    ' - playerLogPane : LogPane
    - state : BattleUIState
    ' - movePane : MovePane
    ' - DefinitionPopup : DefinitionPopUp
    ' - MovePopup : MovePopUp
    ' + <<override>> _Ready() 
    + WaitForEnemyMove() 
    + PlayerTurn() 
    - Close() 
    ' - GetLogPane(target:Target) : LogPane
    ' + LogAttack(word:string, target:Target) 
    ' + LogDefend(word:string, target:Target) 
    ' + LogAttackStatus(status:AttackStatus, target:Target) 
}
' Control <|-- BattleUI

BattleUI "1" *-- "2" LogPane
BattleUI "1" *-- "2" HealthBar
BattleUI "1" *-- "1" MovePane
BattleUI "1" *-- "1" MovePopUp
BattleUI "1" *-- "1" DefinitionPopUp


' BattleUI "1" *-- "1" BattleUIState
@enduml
