@startuml
enum Target {
    Player,
    Enemy,
}
enum BattleUIState {
    SelectWord,
    ViewDefinition,
    SelectMove,
    EnemyMove,
}
class BattleUI <<partial>> {
    - enemyHealthBar : HealthBar
    - playerHealthBar : HealthBar
    - enemyLogPane : LogPane
    - playerLogPane : LogPane
    - state : BattleUIState
    - movePane : MovePane
    - currentHealth : int
    + CurrentHealth : int <<get>>
    - maxHealth : int
    + MaxHealth : int <<get>>
    - DefinitionPopup : DefinitionPopUp
    - MovePopup : MovePopUp
    + <<override>> _Ready() : void
    + WaitForEnemyMove() : void
    + PlayerTurn() : void
    + UpdatePlayerLog(player:Character) : void
    + UpdateEnemyLog(enemy:Character) : void
    + UpdateMoves(moves:Move[]) : void
    + UpdatePlayerHealth(healthPercent:double) : void
    + UpdateEnemyHealth(healthPercent:double) : void
    <<internal>> Close() : void
    - GetLogPane(target:Target) : LogPane
    + LogAttack(word:string, target:Target) : void
    + LogDefend(word:string, target:Target) : void
    + LogAttackStatus(status:AttackStatus, target:Target) : void
}
Control <|-- BattleUI
@enduml
