@startuml Card
class Card {
    - hoverAmmount : float
    - helpText : String
    - helpClickedTest : String
    - word : String <<get>>
    - helpButton : Label <<get>>
    - hoverTween : Tween
    + <<override>> _Ready() : void
    + HoverBy(ammount:Vector2) : void
    - _on_mouse_entered() : void
    - _on_mouse_exited() : void
    - _on_gui_input(@event:InputEvent) : void
    + SetLabel(text:String) : void
}
' Control <|-- Card
@enduml
