@startuml Card
class Card {
    - hoverAmmount : float
    - helpText : String
    - helpClickedTest : String
    - word : String <<get>>
    - helpButton : Label <<get>>
    - hoverTween : Tween
    + <<override>> _Ready() 
    + HoverBy(ammount:Vector2) 
    - _on_mouse_entered() 
    - _on_mouse_exited() 
    - _on_gui_input(@event:InputEvent) 
    + SetLabel(text:String) 
}
' Control <|-- Card
@enduml
