@startuml Character

abstract class Character {
    + CurrentHealth : double 
    # baseDamage : int
    + Armor : double
    + Type : string
    + MaxHealth : double
    / PercentHealth : double
    + KnownMoves : Move [*]
    + CurrentMoves : Move [*]
    / IsAlive : bool
    + SelectRandomMove() : Move
    + SelectRandomMove(effectiveAgainst:Character, type:MoveType) : Move
    + SelectMoveType() : MoveType
    # RandomizeType() : void
    + SelectMoves(count:int, target:Character) : void
    + FullHeal() : void
    + ResetArmor() : void
    + Attack(move:Move, target:Character) : AttackStatus
    + Defend(move:Move) : void
    + ApplyDamage(damage:float) : void
    + Heal(ammount:float) : void
}
' Area2D <|-- Character
ISaveable <|-- Character

Character "*" *-- "1..*" Move

@enduml
