@startuml Character

abstract class Character {
    + CurrentHealth : double 
    # baseDamage : int
    + Armor : double
    + Type : string
    + MaxHealth : double
    / PercentHealth : double
    ' + KnownMoves : Move [*]
    + CurrentMoves : Move [*]
    / IsAlive : bool
    + SelectRandomMove() : Move
    + SelectRandomMove(effectiveAgainst:Character, type:MoveType) : Move
    + SelectMoveType() : MoveType
    # RandomizeType() 
    + SelectMoves(count:int, target:Character) 
    + FullHeal() 
    + ResetArmor() 
    + Attack(move:Move, target:Character) : AttackStatus
    + Defend(move:Move) 
    + ApplyDamage(damage:float) 
    + Heal(ammount:float) 
}
' Area2D <|-- Character
ISaveable <|.. Character

Character "*" *-- "1..*" Move : Knows

@enduml
