@startuml DefinitionPopUp
class DefinitionPopUp  {
    + Text : string 
    + Word : string
    + Close() : void
}
' PanelContainer <|-- DefinitionPopUp

BattleUI "1" *-- "1" DefinitionPopUp
ExitPane "1" *-- "1" Button
@enduml
