@startuml DefinitionPopUp
class DefinitionPopUp  {
    + Text : string 
    + Word : string
    + Close() 
}
' PanelContainer <|-- DefinitionPopUp

BattleUI "1" *-- "1" DefinitionPopUp
DefinitionPopUp "1" *-- "1" Button
@enduml
