@startuml
class Enemy <<partial>> {
    - icon : AnimatedSprite2D
    - rand : Random
    + selectRandomMove() : Move
    + <<override>> Attack(move:Move, target:Character) : void
    + <<override>> Defend(move:Move) : void
    + <<override>> Load(dict:Dictionary<string, JsonElement>) : void
    + <<override>> Save() : Dictionary<string, object>
    + <<override>> _Ready() : void
    - InteractionAreaEntered(body:Area2D) : void
    - InteractionAreaExited(body:Area2D) : void
}
Character <|-- Enemy
ISaveable <|-- Enemy
@enduml
