@startuml
class Enemy <<partial>> {
    - icon : AnimatedSprite2D
    + <<override>> Load(dict:Dictionary<string, JsonElement>) : void
    + <<override>> Save() : Dictionary<string, object>
    + <<override>> _Ready() : void
    - InteractionAreaEntered(body:Area2D) : void
    - InteractionAreaExited(body:Area2D) : void
}
Character <|-- Enemy
ISaveable <|-- Enemy
@enduml
