@startuml Hub

class HubWorld{
    - ENEMY_COUNT : int = 5
    - NUMBER_OF_MOVES : int = 5
    + PlayerWin() : void
    + PlayerLose() : void
    - State: GameState
    + PlayerAttack(word:string) : void
    + PlayerDefend(word:string) : void
    - TriggerEnemyAction() : void
    - SaveAndQuit() : void
    - Quit() : void
    - SpawnEnemies() : void
    - StartBattle(enemy:Character) : void
    - ExitBattle() : void
    + RespawnEnemies() : void
}
' Node2D <|-- HubWorld
ISaveable <|.. HubWorld

' HubWorld "1" *-- "1" GameState
HubWorld "1" o-- "1" Player
HubWorld "1" o-- "1" BattleUI
HubWorld "1" o-- "1" InfoPane
HubWorld "1" o-- "1" ExitPane
HubWorld "1" o-- "5" Enemy

' HubWorld "1" *-- "1" Timer
' HubWorld "1" *-- "1" Camera2D

' ISaveable <[hidden]- HubWorld

@enduml
