@startuml InfoPane
class InfoPane  {
    ' - wordContainer : GridContainer
    ' - playerType : Label
    ' - stats : Label
    ' - player : Player
    ' + <<override>> _Ready() 
    - Display() 
    ' - UpdatePlayerInfo() 
    + ClearWords() 
    - DisplayWordInfo(word:string) 
    + AddWord(word:string) 
}
' PanelContainer <|-- InfoPane
@enduml
