@startuml MainMenu
class MainMenu {
    ' - controlPanel : Panel
    ' + <<override>> _Ready() 
    ' - _on_start_pressed() 
    ' - _on_controls_pressed() 
    ' - _on_about_pressed() 
    ' - _on_exit_pressed() 
    ' - _on_close_control_pressed() 
}
' Control <|-- MainMenu
MainMenu -- HubWorld: Loads
MainMenu "1" *-- "4" Button 
@enduml
