@startuml
class MainMenu <<partial>> {
    - controlPanel : Panel
    + <<override>> _Ready() : void
    - _on_start_pressed() : void
    - _on_controls_pressed() : void
    - _on_about_pressed() : void
    - _on_exit_pressed() : void
    - _on_close_control_pressed() : void
}
Control <|-- MainMenu
@enduml
