@startuml
class MovePane <<partial>> {
    - cardScene : PackedScene
    - moveContainer : HBoxContainer
    + <<override>> _Ready() : void
    + ClearMoves() : void
    + AddMove(move:Move) : Card
}
Control <|-- MovePane
@enduml
