@startuml MovePopUp
class MovePopUp  {
    ' + <<override>> _Ready() 
    + Text : String 
    ' - _on_attack_button_pressed() 
    ' - _on_defend_button_pressed() 
    ' - _on_exit_button_pressed() 
    + Close() 
}
' PanelContainer <|-- MovePopUp
@enduml
