@startuml MovePane
class MovePane  {
    ' - cardScene : PackedScene
    ' - moveContainer : HBoxContainer
    ' + <<override>> _Ready() : void
    + ClearMoves() : void
    + AddMove(move:Move) : Card
}
' Control <|-- MovePane
MovePane "1" *-- "3" Button
@enduml
