@startuml Player
class Player {
    + CanMove : bool
    + BattlesWon : int
    - TryEnterBattle() : bool
    + Move(ammount:Vector2) 
}
Character <|-- Player
' sprite
' Player "*" o-- "1" AnimatedSprite2D
' interaction area
' Player "1" *-- "1" Area2D : Interaction Area
@enduml
