@startuml include
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam groupInheritance 1
' left to right direction
!include ./scripts/Enums.puml
!include ./scripts/Move.puml

together {
    !include ./scenes/Character.puml
    !include ./scenes/Enemy.puml
    !include ./scenes/Player.puml
}
together {
    !include ./scenes/BattleUI.puml
    ' !include ./scenes/Card.puml
    !include ./scenes/DefinitionPopUp.puml
    !include ./scenes/ExitPane.puml
    !include ./scenes/InfoPane.puml
    !include ./scenes/MainMenu.puml
    !include ./scenes/MovePane.puml
    !include ./scenes/MovePopUp.puml
    !include ./scripts/HealthBar.puml
    !include ./scripts/LogPane.puml
    ' !include ./scenes/ControlInfo.puml
}

together{
    !include ./scenes/Globals.puml
    !include ./scripts/WordManager.puml
}

!include ./scenes/HubWorld.puml
' !include ./scripts/Battle.puml
' !include ./scripts/Extension.puml
!include ./scripts/ISaveable.puml

' ISaveable -up[hidden]- Globals
' WordManager -u[hidden]- Player

hide Button

@enduml
