@startuml
class Battle <<partial>> {
    - enemyHealthBar : HealthBar
    - playerHealthBar : HealthBar
    - enemyLogPane : LogPane
    - playerLogPane : LogPane
    - movePane : MovePane
    + <<override>> _Ready() : void
    + <<override>> _Process(delta:double) : void
}
Control <|-- Battle
@enduml
