@startuml Battle
class Battle {
    - enemyHealthBar : HealthBar
    - playerHealthBar : HealthBar
    - enemyLogPane : LogPane
    - playerLogPane : LogPane
    - movePane : MovePane
}
' Control <|-- Battle
@enduml
