@startuml LogPane
' record MoveLog  {
'     + Word : string <<get>> <<init>>
'     + Type : MoveType <<get>> <<init>>
'     + <<override>> ToString() : string
' }
class LogPane  {
    ' - messageContainer : VBoxContainer
    ' - messageLabel : RichTextLabel
    ' - logLabel : Label
    - log : Queue<object>
    ' + Label : string <<get>> <<set>>
    ' + <<override>> _Ready() : void
    + LogMove(move:string, type:MoveType) : void
    + Log(item:T) : void
    + Clear() : void
    ' + <<override>> _Process(delta:double) : void
}
' Control <|-- LogPane
@enduml
