@startuml WordManager

' class RelationExtension <<static>> {
'     + {static} DamageMultiplier(relation:Relation) : double
'     + {static} DefenseMultiplier(relation:Relation) : double
' }
' class RelationJsonConverter {
'     + <<override>> Read(reader:Utf8JsonReader, typeToConvert:Type, options:JsonSerializerOptions) : Relation
'     + <<override>> Write(writer:Utf8JsonWriter, value:Relation, options:JsonSerializerOptions) 
' }
record CategoryInfo  {
    + Type : string
    + Relation : Relation
}
record WordInfo {
    + Word : string 
    ' + Types : CategoryInfo[*]
    + Definitions : string[1..*]
}
WordInfo "*" *-- "1..*" CategoryInfo : Types

class WordManager{
    ' {static} - WordData : Dictionary<string, WordInfo>
    / {static} Words : IEnumerable<string>
    / {static} AllMoves : IEnumerable<Move> 
    / {static} AllTypes : IEnumerable<string> 
    + {static} GetDefinitions(word:string) : IEnumerable<string>
    - {static} GetOfRelation(word:string, relation:Relation) : IEnumerable<string>
    + {static} GetSynonyms(word:string) : IEnumerable<string>
    + {static} GetSynonyms(word:WordInfo) : IEnumerable<string>
    + {static} GetAntonyms(word:string) : IEnumerable<string>
    + {static} GetAntonyms(word:WordInfo) : IEnumerable<string>
    + {static} GetTypeAntonyms(type:string) : IEnumerable<string>
    + {static} GetTypeSynonyms(type:string) : IEnumerable<string>
    + {static} RandomTypes(count:int) : IEnumerable<string>
    + {static} RandomMoves(count:int) : IEnumerable<Move>
    + {static} RandomWords(count:int) : IEnumerable<string>
    + {static} AreSynonyms(word1:string, word2:string) : bool
    + {static} AreAntonyms(word1:string, word2:string) : bool
    + {static} ClassifyRelation(word:string, type:string) : Relation
}
' "JsonConverter`1" "<Relation>" <|-- RelationJsonConverter
' Node <|-- WordManager

WordManager "1" *-- "1..*" WordInfo : Dictionary

WordManager <|-- Character: Checks Words With
@enduml
